sudo: required
dist: xenial
addons:
  chrome: stable
language: node_js
services:
- xvfb
cache:
  yarn: true
node_js:
- "10"
cache:
- node_modules
before_install:
- npm i -g yarn
install:
- yarn install
script:
- yarn run test -f autoformat --reporter=dots --production --coverage
- codecov -F autoformat
# - yarn run docs:api --validate-only # @todo bring it back, commented out to speed up the execution
