sudo: required
dist: xenial
addons:
  chrome: stable
language: node_js
services:
- xvfb
cache:
  yarn: true
node_js:
- "10"
cache:
- node_modules
before_install:
- npm i -g yarn
install:
- yarn install
script:
- yarn run test --reporter=dots --production --coverage --files='*'
- yarn run docs:api --validate-only
