codecov:
  require_ci_to_pass: false
  notify:
    # CI is also used for building and checking the docs. It takes some time so there's no need to wait for it.
    wait_for_ci: false

coverage:
  coverage.range: 100..100
  status:
    project:
      default:
        target: 100%
        threshold: 0%
        paths:
          - "packages"
        if_not_found: failure
        # if_ci_failed: error

parsers:
  javascript:
    enable_partials: yes