coverage:
  status:
    project:
      target: 100%
flags:
  adapter_ckfinder:
    paths:
      - packages/ckeditor5-adapter-ckfinder
  alignment:
    paths:
      - packages/ckeditor5-alignment
  autoformat:
    paths:
      - packages/ckeditor5-autoformat
  autosave:
    paths:
      - packages/ckeditor5-autosave
  basic_styles:
    paths:
      - packages/ckeditor5-basic-styles
  block_quote:
    paths:
      - packages/ckeditor5-block-quote
  build_balloon:
    paths:
      - packages/ckeditor5-build-balloon
  build_balloon_block:
    paths:
      - packages/ckeditor5-build-balloon-block
  build_classic:
    paths:
      - packages/ckeditor5-build-classic
  build_decoupled_document:
    paths:
      - packages/ckeditor5-build-decoupled-document
  build_inline:
    paths:
      - packages/ckeditor5-build-inline
  ckfinder:
    paths:
      - packages/ckeditor5-ckfinder
  clipboard:
    paths:
      - packages/ckeditor5-clipboard
  cloud_services:
    paths:
      - packages/ckeditor5-cloud-services
  code_block:
    paths:
      - packages/ckeditor5-code-block
  core:
    paths:
      - packages/ckeditor5-core
  easy_image:
    paths:
      - packages/ckeditor5-easy-image
  editor_balloon:
    paths:
      - packages/ckeditor5-editor-balloon
  editor_classic:
    paths:
      - packages/ckeditor5-editor-classic
  editor_decoupled:
    paths:
      - packages/ckeditor5-editor-decoupled
  editor_inline:
    paths:
      - packages/ckeditor5-editor-inline
  engine:
    paths:
      - packages/ckeditor5-engine
  enter:
    paths:
      - packages/ckeditor5-enter
  essentials:
    paths:
      - packages/ckeditor5-essentials
  font:
    paths:
      - packages/ckeditor5-font
  heading:
    paths:
      - packages/ckeditor5-heading
  highlight:
    paths:
      - packages/ckeditor5-highlight
  horizontal_line:
    paths:
      - packages/ckeditor5-horizontal-line
  image:
    paths:
      - packages/ckeditor5-image
  indent:
    paths:
      - packages/ckeditor5-indent
  link:
    paths:
      - packages/ckeditor5-link
  list:
    paths:
      - packages/ckeditor5-list
  markdown_gfm:
    paths:
      - packages/ckeditor5-markdown-gfm
  media_embed:
    paths:
      - packages/ckeditor5-media-embed
  mention:
    paths:
      - packages/ckeditor5-mention
  page_break:
    paths:
      - packages/ckeditor5-page-break
  paragraph:
    paths:
      - packages/ckeditor5-paragraph
  paste_from_office:
    paths:
      - packages/ckeditor5-paste-from-office
  remove_format:
    paths:
      - packages/ckeditor5-remove-format
  restricted_editing:
    paths:
      - packages/ckeditor5-restricted-editing
  special_characters:
    paths:
      - packages/ckeditor5-special-characters
  table:
    paths:
      - packages/ckeditor5-table
  theme_lark:
    paths:
      - packages/ckeditor5-theme-lark
  typing:
    paths:
      - packages/ckeditor5-typing
  ui:
    paths:
      - packages/ckeditor5-ui
  undo:
    paths:
      - packages/ckeditor5-undo
  upload:
    paths:
      - packages/ckeditor5-upload
  utils:
    paths:
      - packages/ckeditor5-utils
  watchdog:
    paths:
      - packages/ckeditor5-watchdog
  widget:
    paths:
      - packages/ckeditor5-widget
  word_count:
    paths:
      - packages/ckeditor5-word-count
