coverage:
  status:
    project:
      target: 100%
flags:
  adapterckfinder:
    paths:
      - packages/ckeditor5-adapter-ckfinder
  alignment:
    paths:
      - packages/ckeditor5-alignment
  autoformat:
    paths:
      - packages/ckeditor5-autoformat
  autosave:
    paths:
      - packages/ckeditor5-autosave
  basicstyles:
    paths:
      - packages/ckeditor5-basic-styles
  blockquote:
    paths:
      - packages/ckeditor5-block-quote
  buildballoon:
    paths:
      - packages/ckeditor5-build-balloon
  buildballoonblock:
    paths:
      - packages/ckeditor5-build-balloon-block
  buildclassic:
    paths:
      - packages/ckeditor5-build-classic
  builddecoupleddocument:
    paths:
      - packages/ckeditor5-build-decoupled-document
  buildinline:
    paths:
      - packages/ckeditor5-build-inline
  ckfinder:
    paths:
      - packages/ckeditor5-ckfinder
  clipboard:
    paths:
      - packages/ckeditor5-clipboard
  cloudservices:
    paths:
      - packages/ckeditor5-cloud-services
  codeblock:
    paths:
      - packages/ckeditor5-code-block
  core:
    paths:
      - packages/ckeditor5-core
  easyimage:
    paths:
      - packages/ckeditor5-easy-image
  editorballoon:
    paths:
      - packages/ckeditor5-editor-balloon
  editorclassic:
    paths:
      - packages/ckeditor5-editor-classic
  editordecoupled:
    paths:
      - packages/ckeditor5-editor-decoupled
  editorinline:
    paths:
      - packages/ckeditor5-editor-inline
  engine:
    paths:
      - packages/ckeditor5-engine
  enter:
    paths:
      - packages/ckeditor5-enter
  essentials:
    paths:
      - packages/ckeditor5-essentials
  font:
    paths:
      - packages/ckeditor5-font
  heading:
    paths:
      - packages/ckeditor5-heading
  highlight:
    paths:
      - packages/ckeditor5-highlight
  horizontalline:
    paths:
      - packages/ckeditor5-horizontal-line
  image:
    paths:
      - packages/ckeditor5-image
  indent:
    paths:
      - packages/ckeditor5-indent
  link:
    paths:
      - packages/ckeditor5-link
  list:
    paths:
      - packages/ckeditor5-list
  markdowngfm:
    paths:
      - packages/ckeditor5-markdown-gfm
  mediaembed:
    paths:
      - packages/ckeditor5-media-embed
  mention:
    paths:
      - packages/ckeditor5-mention
  pagebreak:
    paths:
      - packages/ckeditor5-page-break
  paragraph:
    paths:
      - packages/ckeditor5-paragraph
  pastefromoffice:
    paths:
      - packages/ckeditor5-paste-from-office
  removeformat:
    paths:
      - packages/ckeditor5-remove-format
  restrictedediting:
    paths:
      - packages/ckeditor5-restricted-editing
  specialcharacters:
    paths:
      - packages/ckeditor5-special-characters
  table:
    paths:
      - packages/ckeditor5-table
  themelark:
    paths:
      - packages/ckeditor5-theme-lark
  typing:
    paths:
      - packages/ckeditor5-typing
  ui:
    paths:
      - packages/ckeditor5-ui
  undo:
    paths:
      - packages/ckeditor5-undo
  upload:
    paths:
      - packages/ckeditor5-upload
  utils:
    paths:
      - packages/ckeditor5-utils
  watchdog:
    paths:
      - packages/ckeditor5-watchdog
  widget:
    paths:
      - packages/ckeditor5-widget
  wordcount:
    paths:
      - packages/ckeditor5-word-count
