coverage:
  status:
    project:
      target: 90% # todo, make it 100
      threshold: 5%
flags:
  autoformat:
    paths:
      - packages/ckeditor5-autoformat
  block-quote:
    paths:
      - packages/ckeditor5-block-quote